### ISSUE TITLE
能否自定义接口，且支持自己的key

### ISSUE THREAD

**Issue by wujt1084** [akl7777777/ShellGPT#13]
如题

**Comment by akl7777777** [comment]
你好,可以的,现在已经支持插件系统,我有空出一个详细的插件编写教程,还有插件模板,这样就可以自己编写插件请求自己的服务,插到自己的客户端里面用了

**Comment by akl7777777** [comment]
@wujt1084 你好,插件模板已经分享出来 https://github.com/akl7777777/free-chatgpt-client-pub/blob/main/testPluginDemo105.js 参考一下这个,菜单栏选择添加插件即可

**Comment by wujt1084** [comment]
收到，谢谢

**Comment by akl7777777** [comment]
已支持几个自己填key的线路
<img width="1036" alt="image" src="https://github.com/akl7777777/free-chatgpt-client-pub/assets/84266551/d6f777e2-6766-4759-892c-babeaf9cd1ca">
