### ISSUE TITLE
关于用户体验

### ISSUE THREAD

**Issue by HelloBush** [akl7777777/ShellGPT#16]
软件交互性做的很好，如果能够进一步将界面(提问与回答)的**颜色和字体**优化一下，用户体验会好很多，可以参考官方的配色，当前颜色有点影响输出后markdown中的代码和一些其他格式化文本的阅读。

**Comment by akl7777777** [comment]
好的,感谢建议,后面可能会考虑做多种配色给用户自己切换,然后代码块的功能还在研究中..

**Comment by lecai** [comment]
@HelloBush . 兄弟，咨询下你那java的mhxy_demo，我现在本地编译的时候遇到了一些关于大漠的基础错误。google下来后没有解决。能有时间帮我看下吗？万分感谢。
1、本地java虚拟机crash了。版本：java1.8
2、can not co-create object
核心这两个问题

**Comment by HelloBush** [comment]
好久没有接触Java和维护这个东西了，可能是大漠没有注册吧

**Comment by HelloBush** [comment]
> @HelloBush . 兄弟，咨询下你那java的mhxy_demo，我现在本地编译的时候遇到了一些关于大漠的基础错误。google下来后没有解决。能有时间帮我看下吗？万分感谢。 1、本地java虚拟机crash了。版本：java1.8 2、can not co-create object 核心这两个问题

好久没有接触Java和维护这个东西了，可能是大漠没有注册吧
