### ISSUE TITLE
希望增加的功能

### ISSUE THREAD

**Issue by liu-101** [akl7777777/ShellGPT#17]
现阶段只能有一个聊天记录，而且退出软件后聊天记录会清空，除非自己导出。希望增加一个像官网那种左边有历史对话的功能，会方便很多

**Comment by akl7777777** [comment]
已支持历史聊天记录
<img width="1036" alt="image" src="https://github.com/akl7777777/free-chatgpt-client-pub/assets/84266551/c326a7e0-4568-49fb-88b4-ec9329e5fa44">
<img width="1036" alt="image" src="https://github.com/akl7777777/free-chatgpt-client-pub/assets/84266551/d43b3a83-87bb-4a54-9fd6-48af831e3a1b">
