### ISSUE TITLE
Linux安装报错

### ISSUE THREAD

**Issue by IamJasonBoy** [akl7777777/ShellGPT#21]
[root@10-27-70-11 ~]# dpkg -i OpenAi-ChatGPT_3.3.2_amd64.deb 
Selecting previously unselected package openai-chatgpt.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack OpenAi-ChatGPT_3.3.2_amd64.deb ...
Unpacking openai-chatgpt (3.3.2) ...
dpkg-deb (subprocess): cannot copy archive member from 'OpenAi-ChatGPT_3.3.2_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive 'OpenAi-ChatGPT_3.3.2_amd64.deb' (size=11567104) member 'data.tar': lzma error: unexpected end of input
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive OpenAi-ChatGPT_3.3.2_amd64.deb (--install):
 cannot copy extracted data for './opt/OpenAi-ChatGPT/resources/app.asar' to '/opt/OpenAi-ChatGPT/resources/app.asar.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 OpenAi-ChatGPT_3.3.2_amd64.deb

**Comment by akl7777777** [comment]
我这边找了个机器试了下,可以安装没有报错啊,怀疑是之前的那个包有问题,要不你下载最新的包再试试?
