### ISSUE TITLE
用官网反向代理的方式对话之后，导致官网中对应产生的对话点击后卡死

### ISSUE THREAD

**Issue by everiori** [akl7777777/ShellGPT#24]
获取accesstoken后，使用官网反向代理的方式进行对话，对话过程没问题，然后访问ChatGPT官网，点击刚才生成的对话，发现浏览器标签页卡死，该对话也无法删除，请协助看一下是什么问题。谢谢。

**Comment by akl7777777** [comment]
官网现在应该优化了吧,不会卡死了

**Comment by akl7777777** [comment]
我看了一下,官网好像已经优化了显示,不会卡死了;之前可能是因为反代没有总结这次的对话,导致页面渲染的时候无法获取对话的概要信息从而卡死,现在官网优化了
