### ISSUE TITLE
英文单词换行时无法正常连在一起显示

### ISSUE THREAD

**Issue by wwejwwej** [akl7777777/ShellGPT#25]
在默认模式下，英文单词换行时被强行断开，比如到了行末的时间hi就会强行断开就变成了h
i
                                                              hello变成h
ello

**Comment by wwejwwej** [comment]
回答的英文单词不能连在一起连在一起真的很要命呀. 大家不要英文吗, 比如到了行末的时间github就会强行断开变成gi
thub
难不难受?

**Comment by akl7777777** [comment]
OK,感觉应该可以用CSS解决,我研究下

**Comment by akl7777777** [comment]
已修复,下载最新包试试

**Comment by wwejwwej** [comment]
谢谢,这个问题已修复.


谢谢!


有个显示的格式问题, 你看正版官网回复, 每段之间是有段间距的. 


但是咱们软件回复的没有段间距, 我把窗口最大化的时候, 根本看不清段落分割, 对英文影响明显, 如图。


能调整下吗, 万分感谢!   



















在 2023-07-10 00:14:00，"akl7777777" ***@***.***> 写道：

已修复,下载最新包试试

**Comment by wwejwwej** [comment]
我想上传图，但传不了。
