### ISSUE TITLE
高CPU占用问题

### ISSUE THREAD

**Issue by Username-Adrian** [akl7777777/ShellGPT#36]
这是一个很棒的产品，所以我想将这个软件常驻后台，但是他一直占用我的CPU，即使我什么都没干。
![image](https://github.com/akl7777777/ShellGPT/assets/47768706/b0eae60c-5245-46a4-a8cf-742ad51b7107)

**Comment by akl7777777** [comment]
可以尝试升级最新版客户端,然后把这两项取消勾选
<img width="805" alt="image" src="https://github.com/akl7777777/ShellGPT/assets/84266551/ede29157-f2e6-48b9-a915-9847154926c2">

**Comment by Username-Adrian** [comment]
> 可以尝试升级最新版客户端,然后把这两项取消勾选 <img alt="image" width="805" src="https://user-images.githubusercontent.com/84266551/248208484-ede29157-f2e6-48b9-a915-9847154926c2.png">

很棒的回答，完美地解决了我的问题！
