### ISSUE TITLE
昨天还能用，今天就不行了

### ISSUE THREAD

**Issue by weasonn** [akl7777777/ShellGPT#37]
![0628221018](https://github.com/akl7777777/ShellGPT/assets/27633819/b20f8092-edf7-49be-abe9-5087c065b38e)

**Comment by akl7777777** [comment]
尝试删除Windows目录C:\Users\Administrator\AppData\Roaming\OpenAi-ChatGPT
下的所有文件,重启软件再试,如果不行,建议关闭杀毒,下载最新版,放C盘试试,一般都能解决

**Comment by weasonn** [comment]
> 尝试删除Windows目录C:\Users\Administrator\AppData\Roaming\OpenAi-ChatGPT 下的所有文件,重启软件再试,如果不行,建议关闭杀毒,下载最新版,放C盘试试,一般都能解决

大佬666
