### ISSUE TITLE
可以支持Claude2和bard吗？非常期待

### ISSUE THREAD

**Issue by ai1li1er1** [akl7777777/ShellGPT#42]
这两款AI升级之后用起来很顺手，希望能在ShellGpt直接使用，谢谢

**Comment by Daqiv** [comment]
胆大妄为 ! 同求 嘿嘿嘿!

**Comment by akl7777777** [comment]
Claude2-100k已经加在Pro线路里面了(这个比较特殊,由于本地的一些限制,只能放在服务端运行),当然这个是限制次数的,可能要清缓存才可以看到,先用着吧,完全免费的Claude2后期再找找..

**Comment by ai1li1er1** [comment]
万分感谢！！！
