### ISSUE TITLE
GPT3.5完全没有反应啊

### ISSUE THREAD

**Issue by hito0512** [akl7777777/ShellGPT#46]
gpt3.5-turbo任何问题都不回答，请问这是什么情况

**Comment by akl7777777** [comment]
左上角更换线路即可,国内1一般都是可以的

**Comment by hito0512** [comment]
> 左上角更换线路即可,国内1一般都是可以的

没有啊，我换了很多的线路，gpt4勉强可以用，bing反应很慢，其他的线路一律没有任何反应，之前3.5反应还是很快的，我电脑ip是不是被锁定了，可我设置的是动态ip

**Comment by akl7777777** [comment]
国内1试过了吗

**Comment by akl7777777** [comment]
刚看了一下,国内1好像确实不行了,等会修复

**Comment by hito0512** [comment]
> 刚看了一下,国内1好像确实不行了,等会修复

国内1有时候可以，晚上效果不太好，总是卡主，其他线路我需要弄daili吗？其他的线路感觉完全没有反应啊，包括显示的那个最快的那个线路

**Comment by akl7777777** [comment]
先用国内96吧,这个我刚刚试过还可以

**Comment by hito0512** [comment]
> 先用国内96吧,这个我刚刚试过还可以

感谢回复，感谢分享！！

**Comment by akl7777777** [comment]
已修复,刚刚新增国内97(new)线路,重启软件即可享受,超级快

**Comment by akl7777777** [comment]
<img width="1036" alt="image" src="https://github.com/akl7777777/ShellGPT/assets/84266551/4b408476-dc13-4c25-9967-665dfeee2f8b">
