### ISSUE TITLE
关于壳聊的一些问题

### ISSUE THREAD

**Issue by WBS-ONLINE** [akl7777777/ShellGPT#50]
佬好，主要是用壳聊得软件去用的，最近一直在报这个错
`{
  "error": {
    "message": "当前分组 cheap 下对于模型 gpt-3.5-turbo 计费模式 [按量计费] 无可用渠道 (request id: 20240205112007849270237Q2dobO3l)",
    "type": "shell_api_error"
  }
}
`
希望能得到解决，最近使用从2/4开始一直报错！

**Comment by akl7777777** [comment]
最近免费通道拥挤,正在修复中,稍等啊

**Comment by WBS-ONLINE** [comment]
谢谢佬，希望能尽快恢复正常

**Comment by akl7777777** [comment]
> 谢谢佬，希望能尽快恢复正常

已经可以了,重启软件

**Comment by WBS-ONLINE** [comment]
OK了

**Comment by WBS-ONLINE** [comment]
谢谢佬，希望网站越来越好，本蒟蒻告退

**Comment by WBS-ONLINE** [comment]
佬好，又出现了问题
![屏幕截图 2024-02-08 095921](https://github.com/akl7777777/ShellGPT/assets/112312627/7fc42c64-7253-4e2c-9798-1046f4dce0ff)

**Comment by WBS-ONLINE** [comment]
没人吗

**Comment by akl7777777** [comment]
> 佬好，又出现了问题 ![屏幕截图 2024-02-08 095921](https://private-user-images.githubusercontent.com/112312627/303191049-7fc42c64-7253-4e2c-9798-1046f4dce0ff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDYxNzksIm5iZiI6MTcwNzQwNTg3OSwicGF0aCI6Ii8xMTIzMTI2MjcvMzAzMTkxMDQ5LTdmYzQyYzY0LTcyNTMtNGUyYy05Nzk4LTEwNDZmNGRjZTBmZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxNTI0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzUxNjQ5NDg4ZmQwMjQ3M2FiYjJjMTdkNDQ4ZDk0NjI3N2MzNjUwYzg1MjJkMmMwOTkxNjcxMWIyOTY0Nzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JYDGMu4KJMjoDpTtH3HMf1_hjYgO7MLwKX2lj1_5aMc)

已修复

**Comment by WBS-ONLINE** [comment]
佬好，今天又出现问题
![Uploading 屏幕截图 2024-02-15 151526.jpg…]()

**Comment by akl7777777** [comment]
什么问题,图看不到
