### ISSUE TITLE
希望能增加数学输入，AI的符号回复太难看懂了

### ISSUE THREAD

**Issue by Lucuis-link** [akl7777777/ShellGPT#9]

**Comment by akl7777777** [comment]
不妨详细说说... 你是指的输入数学公式吗,AI回复的又是啥,难看懂,具体说说?

**Comment by Lucuis-link** [comment]
比如
![2023-04-12_090415](https://user-images.githubusercontent.com/130416892/231320744-cabe4a1c-92dc-4956-ac02-77db0cc22ed8.png)

**Comment by akl7777777** [comment]
感谢反馈,请升级最新版的客户端已经修复了数学公式的显示 https://github.com/akl7777777/ShellGPT/releases/tag/v3.5.6

**Comment by akl7777777** [comment]
<img width="1036" alt="image" src="https://github.com/akl7777777/ShellGPT/assets/84266551/3eca6ef1-0376-4c48-8241-57d663a9c726">
